//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Community()
        {
            this.Community_News = new HashSet<Community_News>();
        }
    
        public int community_id { get; set; }
        public string community_name { get; set; }
        public string account { get; set; }
        public string passwd { get; set; }
        public string intro { get; set; }
        public string finish { get; set; }
        public string address { get; set; }
        public string typeOfBuild { get; set; }
        public Nullable<int> total_floor { get; set; }
        public Nullable<int> holders { get; set; }
        public Nullable<int> perOfHolder { get; set; }
        public string manage { get; set; }
        public string company { get; set; }
        public string build { get; set; }
        public string txt_spot { get; set; }
        public string txt_public { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public Nullable<double> age { get; set; }
        public Nullable<int> under_floor { get; set; }
        public Nullable<int> over_floor { get; set; }
        public string map_iframe { get; set; }
        public string group_buying_url { get; set; }
        public string info_content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Community_News> Community_News { get; set; }
    }
}
