//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseDetail = new HashSet<PurchaseDetail>();
        }
    
        public string purchase_no { get; set; }
        public int customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int pay_type { get; set; }
        public int pay_state { get; set; }
        public int ship_state { get; set; }
        public string cancel_reason { get; set; }
        public double total { get; set; }
        public double ship_fee { get; set; }
        public double bank_charges { get; set; }
        public string receive_email { get; set; }
        public string receive_name { get; set; }
        public string receive_tel { get; set; }
        public string receive_mobile { get; set; }
        public string receive_zip { get; set; }
        public string receive_address { get; set; }
        public string receive_memo { get; set; }
        public string remit_no { get; set; }
        public Nullable<System.DateTime> remit_date { get; set; }
        public Nullable<double> remit_money { get; set; }
        public string remit_memo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetail { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
