//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int shipment_id { get; set; }
        public int pay_type { get; set; }
        public int limit_money { get; set; }
        public int shipment_fee { get; set; }
        public int bank_charges { get; set; }
    }
}
